name: gp_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+8
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  chat_gpt_sdk: ^3.0.9
  dash_chat_2: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gpt.png
    - assets/tony.png
    - assets/Logo.png
    - assets/Cbot.png
    - assets/ChatLogo.jpg
    - assets/GptGreen.png
    - assets/GptBlack.png


